export const SET_ERROR = 'SET_ERROR';
export const SET_VALUE = 'SET_VALUE';

// REGISTER FORM
export const SEND_DATA_FETCHPROMISE = 'SEND_DATA_FETCHPROMISE';
export const SET_STEP_FORM = 'SET_STEP_FORM';
