export const SET_DATA_REGIONI = 'SET_DATA_REGIONI';
export const GET_DATA_REGIONI = 'GET_DATA_REGIONI';
export const SET_DATA_PROVINCE = 'SET_DATA_PROVINCE';
export const GET_DATA_PROVINCE = 'GET_DATA_PROVINCE';
export const SET_DATA_COMUNI = 'SET_DATA_COMUNI';
export const GET_DATA_COMUNI = 'GET_DATA_COMUNI';
